version: '3.8'
services:
  places_app:
    container_name: places_app
    build: .
    volumes:
      - ./app:/srv/app
    ports:
      - "1449:1449"
    # Removed ports from here, as Nginx will handle incoming traffic

  nginx:
    image: nginx:latest
    ports:
      - "19:80" # Expose port 80 for HTTP traffic
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - places_app