name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setting up SSH keys
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Connect to Server and Deploy
        run: |
          ssh -o "StrictHostKeyChecking=no" root@167.71.238.26 << 'ENDSSH'
            cd /home/server_projects/Smart-Places-Search
            git pull origin main
            docker-compose up -d --build
          ENDSSH
